
submodule :

path :

  proto : './proto'
  out.debug : './out.debug'
  out.release : './out.release'

reflector :

  .default.common :
    srcFilter :
      basePath : '.'
      prefixPath : './proto'
      maskAll :
        excludeAny :
        - !!js/regexp '/(^|/)-/'

  .default.debug :
    inherit : .default.common
    srcFilter :
      maskAll :
        excludeAny :
        - !!js/regexp '/.release($|.|/)/i'

  .default.release :
    inherit : .default.common
    srcFilter :
      maskAll :
        excludeAny :
        - !!js/regexp '/.debug($|.|/)/i'
        - !!js/regexp '/.test($|.|/)/i'
        - !!js/regexp '/.experiment($|.|/)/i'

  .current :
    reflectMap :
    - .

  .debug :
    inherit :
      - .default.debug
      - .current

  .release :
    inherit :
      - .default.release
      - .current

  .dependencies.current :
    reflectMap :
    - .

  .dependencies.debug :
    inherit :
      - .default.debug
      - .current

  .dependencies.release :
    inherit :
      - .default.release
      - .current

  grab.release :
    reflectMap :
      reflector::.release : path::out.release

  grab.debug :
    reflectMap :
      reflector::.debug : path::out.debug

  grab.dependencies.release :
    reflectMap :
      reflector::.dependencies.release : path::out.release

  grab.dependencies.debug :
    reflectMap :
      reflector::.dependencies.debug : path::out.debug

  out.debug :
    srcFilter :
      basePath : .
    reflectMap :
      - path:out.debug

  out.release :
    srcFilter :
      basePath : .
    reflectMap :
      - path:out.release

step :

  grab.debug :
    inherit : grab
    reflector : reflector::grab.debug
  grab.release :
    inherit : grab
    reflector : reflector::grab.release

  grab.dependencies.debug :
    inherit : grab
    reflector : reflector::grab.dependencies.debug
  grab.dependencies.release :
    inherit : grab
    reflector : reflector::grab.dependencies.release

build :

  .debug :
    default : 1
    setting :
      debug : 1
      raw : 1
      release : 0
      compiled : 0
    steps :
      - step::grab.debug
      - step::grab.dependencies

  .debug.compiled :
    setting :
      debug : 1
      raw : 0
      release : 0
      compiled : 1
    steps :
      - step::grab.debug

  .release.raw :
    setting :
      debug : 0
      raw : 1
      release : 1
      compiled : 0
    steps :
      - step::grab.release

  .release.compiled :
    setting :
      debug : 0
      raw : 0
      release : 1
      compiled : 1
    steps :
      - step::grab.release

  all :
    steps :
      - concurrent :
        - build::.debug
        - build::.release.compiled
